### ISSUE TITLE
Ascension Retranscription Evaluation 7.1.5

### ISSUE THREAD

**Issue by ArthurSrz** [ArthurSrz/phd_dissertation#33]
- [X] Retranscription BFC #1 
- [x] Retranscription Centre #2 
- [x] Retranscription Haute-Garonne #3 
- [ ] Retranscription Orléans Métropôle #4 
- [x] Retranscription Collectivité de Corse #5 
- [x] Retranscription Occitanie #6 
- [ ] Retranscription Avignon #7 
- [x] Retranscription Paris #8 
- [ ] Retranscription Digne #9 
- [x] Retranscription Nevers #10 
- [ ] Retranscription Haute-Garonne #11
- [x] Retranscription Occitanie #1 
- [x] Retranscription Montpellier #1 
- [x] Retranscription Open Data France #1
